name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18, 20, 22]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install CLI dependencies for build
        run: pnpm add commander yaml

      - name: Build project
        run: pnpm run build

      - name: Run tests
        run: pnpm test

      - name: Test library import (no CLI deps)
        run: |
          # Test that the core library works without CLI dependencies
          pnpm remove commander yaml
          node -e "
            import('./dist/mediainfo.js').then(m => {
              const result = m.parseMediaInfo('General\nFormat: MP4\n');
              console.log('✓ Library import test passed');
              console.log('Format:', result.general.format);
            }).catch(e => {
              console.error('✗ Library import test failed:', e.message);
              process.exit(1);
            });
          "

  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install CLI dependencies
        run: pnpm add commander yaml

      - name: Check TypeScript compilation
        run: pnpm exec tsc --noEmit 